services:
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-svc
      - hotel-svc
      - reservation-svc

  user-svc-db:
    image: postgres:18
    env_file:
      - .user-svc-db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - userdb_data:/var/lib/postgresql

  hotel-svc-db:
    image: postgres:18
    env_file:
      - .hotel-svc-db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - hoteldb_data:/var/lib/postgresql

  reservation-svc-db:
    image: postgres:18
    env_file:
      - .reservation-svc-db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - reservation_data:/var/lib/postgresql/data

  user-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args:
        MODULE_PATH: user-svc/svc
    env_file:
      - .user-svc.env
    depends_on:
      user-svc-db:
        condition: service_healthy
      activemq:
        condition: service_healthy
    ports:
      - "8080"

  hotel-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args:
        MODULE_PATH: hotel-svc/svc
    env_file:
      - .hotel-svc.env
    depends_on:
      hotel-svc-db:
        condition: service_healthy
      activemq:
        condition: service_healthy
    ports:
      - "8080"

  reservation-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args:
        MODULE_PATH: reservation-svc/svc
    env_file:
      - .reservation-svc.env
    depends_on:
      reservation-svc-db:
        condition: service_healthy
    ports:
      - "8080"

volumes:
  userdb_data:
  hoteldb_data:
  reservation_data: