services:
  eureka-server:
    image: crooodle-cloud-eureka-server:latest
    container_name: eureka-server
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args:
        MODULE_PATH: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 20

  api-gateway:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args:
        MODULE_PATH: api-gateway
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  user-svc-db:
    image: postgres:18
    env_file: [.user-svc-db.env]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - userdb_data:/var/lib/postgresql/data

  hotel-svc-db:
    image: postgres:18
    env_file: [.hotel-svc-db.env]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - hoteldb_data:/var/lib/postgresql/data

  reservation-svc-db:
    image: postgres:18
    env_file: [.reservation-svc-db.env]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - reservation_data:/var/lib/postgresql/data

  user-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args: { MODULE_PATH: user-svc/svc }
    env_file: [.user-svc.env]
    environment:
      - SPRING_APPLICATION_NAME=user-svc
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      user-svc-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    expose: ["8080"]

  hotel-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args: { MODULE_PATH: hotel-svc/svc }
    env_file: [.hotel-svc.env]
    environment:
      - SPRING_APPLICATION_NAME=hotel-svc
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      hotel-svc-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    expose: ["8080"]

  reservation-svc:
    build:
      context: .
      dockerfile: ./services/module.Dockerfile
      args: { MODULE_PATH: reservation-svc/svc }
    env_file: [.reservation-svc.env]
    environment:
      - SPRING_APPLICATION_NAME=reservation-svc
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      reservation-svc-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    expose: ["8080"]

volumes:
  userdb_data:
  hoteldb_data:
  reservation_data:
