services:
  auth-svc:
    depends_on:
      - config-svc
      - discovery-svc
      - gateway-svc
      - auth-svc-db
    build:
      context: .
      dockerfile: svc.Dockerfile
      args:
        MODULE_PATH: services/auth-svc/svc
    env_file:
      - auth-svc-db.env
    ports:
      - "55000:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  auth-svc-db:
    image: postgres:18
    env_file:
      - auth-svc-db.env
    ports:
      - "55001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - auth_svc_db_data:/var/lib/postgresql/data

  discovery-svc:
    build:
      context: .
      dockerfile: infra.Dockerfile
      args:
        MODULE_PATH: infra/discovery-svc
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  config-svc:
    build:
      context: .
      dockerfile: infra.Dockerfile
      args:
        MODULE_PATH: infra/config-svc
    ports:
      - "8888:8888"
    depends_on:
      - discovery-svc
    volumes:
      - ./configs:/configs
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  gateway-svc:
    build:
      context: .
      dockerfile: infra.Dockerfile
      args:
        MODULE_PATH: infra/gateway-svc
    ports:
      - "8080:8080"
    depends_on:
      - config-svc
      - discovery-svc
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  prometheus:
    image: prom/prometheus:v3.8.0-rc.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.3
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/19004_rev1.json
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards

volumes:
  auth_svc_db_data:

