version: "3.7"

services:
  backend:
    build:
      context: .
    depends_on:
      backend_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      BACKEND_POSTGRES_HOST: backend_postgres

  backend_postgres:
    image: postgres:16.1
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      PGPORT: ${BACKEND_POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
