events {}

http {
    resolver 127.0.0.11 ipv6=off;

    server {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        set $hotel_upstream http://hotel-svc:8080;
        set $user_upstream  http://user-svc:8080;

        location ~ ^/(hotel|room|room-type)(/|$) {
            proxy_pass $hotel_upstream;
        }

        location ~ ^/(user|me|register|login)(/|$) {
            proxy_pass $user_upstream;
        }

        location = /health { return 200 'nginx ok'; add_header Content-Type text/plain; }
    }
}
