http {
    server {
        location ~ ^/(hotel|room|room-type)(/|$) {
            proxy_pass http://hotel-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ~ ^/(internal|me|register|login)(/|$) {
            proxy_pass http://user-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /health { return 200 'nginx ok'; add_header Content-Type text/plain; }
    }
}