apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sc-k8s-discovery
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
