services:
  backend_postgres:
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crooodle
      PGPORT: 5433
      TZ: ${TZ:-Europe/Kyiv}
    ports:
      - "5433:5433"
    volumes:
      - backend_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -p $$PGPORT -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  crooodle_backend:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      backend_postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://backend_postgres:5433/crooodle"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-Europe/Kyiv}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  backend_pgdata:
