FROM amazoncorretto:24.0.2-alpine AS run

ARG ARTIFACT_PATH="./out"

WORKDIR /app

RUN addgroup --system spring && adduser --system --ingroup spring spring
USER spring:spring

COPY ${ARTIFACT_PATH}/app.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]
