spring.application.name=hotel-svc

server.port=8080
spring.datasource.url=jdbc:postgresql://hotel-svc-db:5432/hotel_svc
spring.datasource.username=${DB_USER:hotel_svc_hotel}
spring.datasource.password=${DB_PASS:password123}
spring.jpa.hibernate.ddl-auto=update
spring.cloud.openfeign.client.config.user-svc.url=http://user-svc:8080
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.slo.http.server.requests=200ms,500ms,1s,2s,5s

spring.boot.admin.client.url=http://admin-svc:8080

security.internal.api-key=${API_KEY}

logging.level.feign=DEBUG
