server.port=8080
spring.datasource.url=jdbc:postgresql://hotel-svc-db:5432/hotel_svc
spring.datasource.username=${DB_USER:hotel_svc_hotel}
spring.datasource.password=${DB_PASS:password123}
spring.jpa.hibernate.ddl-auto=update
spring.cloud.openfeign.client.config.user-svc.url=http://user-svc:8080
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

security.internal.api-key=${API_KEY}

logging.level.feign=DEBUG

spring.application.name=hotel-svc
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
