@hotelId = 590ccf27-708c-4d7c-a40d-ba109586357a
@ownerId = 4d504972-04ad-42b2-8545-f2da120c66f7
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjI0NjY5MzMsImV4cCI6MTc2MjQ3MDUzMywicm9sZSI6IlJPTEVfSE9URUxfT1dORVIiLCJ1aWQiOiI0ZDUwNDk3Mi0wNGFkLTQyYjItODU0NS1mMmRhMTIwYzY2ZjcifQ.7_d6JCUaVlR4YjRIrD9w37O_S2ynY-BccMC8IG0QLBBDzkwDbm40MUjqr_FehfTSLaMpdA3R5ZBcm2wBww4JyQ

### CREATE
POST http://localhost/hotel
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Paramount",
  "address": "15 may St. 121, Kyiv",
  "roomCount": 60
}

### READ

GET http://localhost/hotel/{{hotelId}}
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/csv
Accept: text/csv

### READ ALL

GET http://localhost/hotel
Accept: application/json

###

GET http://localhost/hotel/html
Accept: text/html

###

GET http://localhost/hotel/csv
Accept: text/csv

### UPDATE

PUT http://localhost/hotel/{{hotelId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Hotel Sunshine Updated",
  "address": "456 Second St, Kyiv",
  "ownerId": "{{ownerId}}",
  "roomCount": 60
}

### DELETE

DELETE http://localhost/hotel/{{hotelId}}
Authorization: Bearer {{token}}
