@hotelId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

### CREATE
POST http://localhost/hotel
Content-Type: application/json

{
  "name": "Hotel Sunshine",
  "address": "123 Main St, Kyiv",
  "ownerId": "{{hotelId}}",
  "roomCount": 50
}

### READ

GET http://localhost/hotel/{{hotelId}}
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/csv
Accept: text/csv

### READ ALL

GET http://localhost/hotel
Accept: application/json

###

GET http://localhost/hotel/html
Accept: text/html

###

GET http://localhost/hotel/csv
Accept: text/csv

### UPDATE

PUT http://localhost/hotel/{{hotelId}}
Content-Type: application/json

{
  "name": "Hotel Sunshine Updated",
  "address": "456 Second St, Kyiv",
  "ownerId": "{{hotelId}}",
  "roomCount": 60
}

### DELETE

DELETE http://localhost/hotel/{{hotelId}}
