@hotelId = 556b5a01-8e3a-44b1-997b-75c9e6765b5d
@ownerId = 330a4b4e-12cc-4d5c-9fe9-584b1b66864b
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjIyMDcyMzYsImV4cCI6MTc2MjIxMDgzNiwicm9sZSI6IlJPTEVfSE9URUxfT1dORVIiLCJ1aWQiOiIzMzBhNGI0ZS0xMmNjLTRkNWMtOWZlOS01ODRiMWI2Njg2NGIifQ.OUSm4cm205e_oSOHG2DmBjzIitDjPMV1qzhmDfB5RDftgQFux4BJdNKpkaOQ4P5ZF1YtJg71PnpSlhI45U5neQ
### CREATE
POST http://localhost/hotel
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Hotel Sunshine",
  "address": "123 Main St, Kyiv",
  "roomCount": 50
}

### READ

GET http://localhost/hotel/{{hotelId}}
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/csv
Accept: text/csv

### READ ALL

GET http://localhost/hotel
Accept: application/json

###

GET http://localhost/hotel/html
Accept: text/html

###

GET http://localhost/hotel/csv
Accept: text/csv

### UPDATE

PUT http://localhost/hotel/{{hotelId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Hotel Sunshine Updated",
  "address": "456 Second St, Kyiv",
  "ownerId": "{{ownerId}}",
  "roomCount": 60
}

### DELETE

DELETE http://localhost/hotel/{{hotelId}}
Authorization: Bearer {{token}}
