@checkIn = "2025-10-13T00:00:00Z"
@checkOut = "2025-10-14T00:00:00Z"
@roomId = 697ec15c-6bdd-4333-91bc-e68bdbd18eae
@clientToken = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6ImR1bWFvcHVzQGdtYWlsLmNvbSIsImlhdCI6MTc2MzA2NjQ2OSwiZXhwIjoxNzYzMDcwMDY5LCJ1c2VyUm9sZSI6IlJPTEVfVFJBVkVMRVIiLCJ1aWQiOiJhOWMzYTAxNS1jZjRjLTQwODEtYTYxNS00NmU0OGI4MDg3ZjkifQ.vNQ6fyJa_KdYgAfnndgsAJbhOOFd6x2cxjk0GZC018ZUN3Yac6ka_RXnQHch3zA1X8gB2dz08vlyg1mtwtWaJQ
@clientId = 769054f8-aa38-4ea1-be1c-34bf0fd7a355
@ownerId = 4d504972-04ad-42b2-8545-f2da120c66f7
@resId = 4c19876b-f2c4-4d66-bfeb-2d77b49781d9
@ownerToken = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjMwNjYxODIsImV4cCI6MTc2MzA2OTc4MiwidXNlclJvbGUiOiJST0xFX0hPVEVMX09XTkVSIiwidWlkIjoiZjcwN2RmN2ItNWU4MC00MDk5LTg1N2EtMDQ3Mzk4MzkyOTA4In0.HbHwkpyji3cZPo7Y2T1xs6L5BXsulItVqwkCJIs2mXnOflG2HJM00Zz-nB2dqmOQ12fU6mf4Wcd2CUle6U5p-w

### CREATE

POST http://localhost/room/{{roomId}}/reservation
Content-Type: application/json
Authorization: Bearer {{clientToken}}

{
  "checkInDate" : {{checkIn}},
  "checkOutDate" : {{checkOut}}
}

### READ

GET http://localhost/reservation/{{resId}}
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

### CONFIRMATION

POST http://localhost/reservation/{{resId}}/confirm
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
  "checkInDate" : {{checkIn}},
  "checkOutDate" : {{checkOut}}
}
