@hotelId = 590ccf27-708c-4d7c-a40d-ba109586357a
@roomId = a7648c18-4cfa-47f9-946d-5ecfe48c583b
@roomTypeId = eb5d5fce-d8e0-4587-b085-dcfc7cc1d70d
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjI0NTgzMjMsImV4cCI6MTc2MjQ2MTkyMywicm9sZSI6IlJPTEVfSE9URUxfT1dORVIiLCJ1aWQiOiI0ZDUwNDk3Mi0wNGFkLTQyYjItODU0NS1mMmRhMTIwYzY2ZjcifQ.wVFszjM8oyJ6p8xHEdIW4zBeG2WoXCCI7cGfsVCi6fIjiNJrkLutPSRSrlhkngeO1DCyFBG1Iu8PpCvTc2yaqA

### CREATE

POST http://localhost/hotel/{{hotelId}}/room
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "125",
  "roomTypeId": "{{roomTypeId}}"
}

### READ

GET http://localhost/room/{{roomId}}
Accept: application/json

###

GET http://localhost/room/{{roomId}}/html
Accept: text/html

###

GET http://localhost/room/{{roomId}}/csv
Accept: text/csv

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/room/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/room/csv
Accept: text/csv


### READ ALL BY TYPE

GET http://localhost/room-type/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/room-type/{{roomTypeId}}/room/html
Accept: text/html

###

GET http://localhost/room-type/{{roomTypeId}}/room/csv
Accept: text/csv


### READ ALL BY HOTEL AND TYPE

GET http://localhost/hotel/{{hotelId}}/room/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/csv
Accept: text/csv


### UPDATE

PUT http://localhost/room/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{roomId}}",
  "name": "Deluxe Room Updated",
  "type": {
    "id": "{{roomTypeId}}",
    "name": "Deluxe"
  }
}

### DELETE

DELETE http://localhost/room/{{roomId}}
Authorization: Bearer {{token}}
