@hotelId = 590ccf27-708c-4d7c-a40d-ba109586357a
@roomTypeId = eb5d5fce-d8e0-4587-b085-dcfc7cc1d70d
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjI0NTgzMjMsImV4cCI6MTc2MjQ2MTkyMywicm9sZSI6IlJPTEVfSE9URUxfT1dORVIiLCJ1aWQiOiI0ZDUwNDk3Mi0wNGFkLTQyYjItODU0NS1mMmRhMTIwYzY2ZjcifQ.wVFszjM8oyJ6p8xHEdIW4zBeG2WoXCCI7cGfsVCi6fIjiNJrkLutPSRSrlhkngeO1DCyFBG1Iu8PpCvTc2yaqA

### CREATE

POST http://localhost/hotel/{{hotelId}}/room-type
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Deluxe Suite",
  "description": "Spacious suite with sea view",
  "capacity": 3,
  "price" : 1500
}

### READ

GET http://localhost/room-type/{{roomTypeId}}
Accept: application/json

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room-type
Accept: application/json

### UPDATE

PUT http://localhost/room-type/{{roomTypeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{roomTypeId}}",
  "name": "Deluxe Suite Updated",
  "description": "Updated description with balcony access",
  "capacity": 4
}

### DELETE

DELETE http://localhost/room-type/{{roomTypeId}}
Authorization: Bearer {{token}}
