@hotelId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@roomId = 5c3f4a21-1234-4567-89ab-abcdef123456
@roomTypeId = 2a1f4e80-5c6d-4f1a-88b3-9f1234567890

### CREATE

POST http://localhost/hotel/{{hotelId}}/room
Content-Type: application/json

{
  "name": "Deluxe Room",
  "roomTypeId": "{{roomTypeId}}"
}

### READ

GET http://localhost/room/{{roomId}}
Accept: application/json

###

GET http://localhost/room/{{roomId}}/html
Accept: text/html

###

GET http://localhost/room/{{roomId}}/csv
Accept: text/csv

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/room/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/room/csv
Accept: text/csv


### READ ALL BY TYPE

GET http://localhost/room-type/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/room-type/{{roomTypeId}}/room/html
Accept: text/html

###

GET http://localhost/room-type/{{roomTypeId}}/room/csv
Accept: text/csv


### READ ALL BY HOTEL AND TYPE

GET http://localhost/hotel/{{hotelId}}/room/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/csv
Accept: text/csv


### UPDATE

PUT http://localhost/room/{{roomId}}
Content-Type: application/json

{
  "id": "{{roomId}}",
  "name": "Deluxe Room Updated",
  "type": {
    "id": "{{roomTypeId}}",
    "name": "Deluxe"
  }
}

### DELETE

DELETE http://localhost/room/{{roomId}}
