@hotelId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@roomTypeId = 2a1f4e80-5c6d-4f1a-88b3-9f1234567890

### CREATE

POST http://localhost/hotel/{{hotelId}}/room-type
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "name": "Deluxe Suite",
  "description": "Spacious suite with sea view",
  "capacity": 3
}

### READ

GET http://localhost/room-type/{{roomTypeId}}
Accept: application/json

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room-type
Accept: application/json

### UPDATE

PUT http://localhost/room-type/{{roomTypeId}}
Content-Type: application/json

{
  "id": "{{roomTypeId}}",
  "name": "Deluxe Suite Updated",
  "description": "Updated description with balcony access",
  "capacity": 4
}

### DELETE

DELETE http://localhost/room-type/{{roomTypeId}}
Authorization: Bearer <JWT_TOKEN>
