@hotelId = 8799d1b4-a921-4d1d-bb6b-f44d0621e4d8
@roomTypeId = 897787a3-8de6-4a5a-b434-0af4a1cfb821
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjMwNjYxODIsImV4cCI6MTc2MzA2OTc4MiwidXNlclJvbGUiOiJST0xFX0hPVEVMX09XTkVSIiwidWlkIjoiZjcwN2RmN2ItNWU4MC00MDk5LTg1N2EtMDQ3Mzk4MzkyOTA4In0.HbHwkpyji3cZPo7Y2T1xs6L5BXsulItVqwkCJIs2mXnOflG2HJM00Zz-nB2dqmOQ12fU6mf4Wcd2CUle6U5p-w

### CREATE

POST http://localhost/hotel/{{hotelId}}/room-type
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Deluxe Suite",
  "description": "Spacious suite with sea view",
  "capacity": 3,
  "price" : 1500
}

### READ

GET http://localhost/room-type/{{roomTypeId}}
Accept: application/json

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room-type
Accept: application/json

### UPDATE

PUT http://localhost/room-type/{{roomTypeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{roomTypeId}}",
  "name": "Deluxe Suite Updated",
  "description": "Updated description with balcony access",
  "capacity": 4
}

### DELETE

DELETE http://localhost/room-type/{{roomTypeId}}
Authorization: Bearer {{token}}
