@hotelId = 8799d1b4-a921-4d1d-bb6b-f44d0621e4d8
@roomId = 1dad7b6f-1312-4909-a069-23c186442c3f
@roomTypeId = 897787a3-8de6-4a5a-b434-0af4a1cfb821
@token = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjMxMjQ3ODQsImV4cCI6MTc2MzEyODM4NCwidXNlclJvbGUiOiJST0xFX0hPVEVMX09XTkVSIiwidWlkIjoiZjcwN2RmN2ItNWU4MC00MDk5LTg1N2EtMDQ3Mzk4MzkyOTA4In0.Gg0Jfgv7BQE6brETKEMnYtHhD_tR_fWCzULOcJqktY08RQfSRcOTwG2l9oJ1h4sGXrw2JxXwUtxcPxWKAT4Flg

### CREATE

POST http://localhost/hotel/{{hotelId}}/room
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "125",
  "roomTypeId": "{{roomTypeId}}"
}

### READ

GET http://localhost/room/{{roomId}}
Accept: application/json

###

GET http://localhost/room/{{roomId}}/html
Accept: text/html

###

GET http://localhost/room/{{roomId}}/csv
Accept: text/csv

### READ ALL BY HOTEL

GET http://localhost/hotel/{{hotelId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/room/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/room/csv
Accept: text/csv


### READ ALL BY TYPE

GET http://localhost/room-type/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/room-type/{{roomTypeId}}/room/html
Accept: text/html

###

GET http://localhost/room-type/{{roomTypeId}}/room/csv
Accept: text/csv


### READ ALL BY HOTEL AND TYPE

GET http://localhost/hotel/{{hotelId}}/room/{{roomTypeId}}/room
Accept: application/json

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/html
Accept: text/html

###

GET http://localhost/hotel/{{hotelId}}/type/{{roomTypeId}}/csv
Accept: text/csv


### UPDATE

PUT http://localhost/room/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{roomId}}",
  "name": "Deluxe Room Updated",
  "type": {
    "id": "{{roomTypeId}}",
    "name": "Deluxe"
  }
}

### DELETE

DELETE http://localhost/room/{{roomId}}
Authorization: Bearer {{token}}
