@userId = a9c3a015-cf4c-4081-a615-46e48b8087f9
@ownerToken = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6Imhsb21vc29tYUBnbWFpbC5jb20iLCJpYXQiOjE3NjMxNDE5NjYsImV4cCI6MTc2MzE0NTU2NiwidXNlclJvbGUiOiJST0xFX0hPVEVMX09XTkVSIiwidWlkIjoiZjcwN2RmN2ItNWU4MC00MDk5LTg1N2EtMDQ3Mzk4MzkyOTA4In0.yP_8bONB9e_E-cLmVC4_wN7SGGUFJYNzVnsskJVVCdAaMx-El8l0XBYBvVpR7ToLXKSa7hv7jwjJDXTkFX_t1A
@userToken = eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjcm9vb2RsZSIsInN1YiI6ImR1bWFvcHVzQGdtYWlsLmNvbSIsImlhdCI6MTc2MzEzNjg3MiwiZXhwIjoxNzYzMTQwNDcyLCJ1c2VyUm9sZSI6IlJPTEVfVFJBVkVMRVIiLCJ1aWQiOiJhOWMzYTAxNS1jZjRjLTQwODEtYTYxNS00NmU0OGI4MDg3ZjkifQ.yBmHlmpdE2__v_nUXayJJLc0TZI4HDv0l-rD6kuqloDvcnYb--RJDfmJOmfPdIegmsJPbAdX7k_f0o4eSc_DRg
@hotelId = 8799d1b4-a921-4d1d-bb6b-f44d0621e4d8

### REGISTER
POST http://localhost/register
Content-Type: application/json

{
  "name": "Duma Opus",
  "email": "dumaopus@gmail.com",
  "password": "leb1Gayyy",
  "role": "TRAVELER"
}

### REGISTER
POST http://localhost/register
Content-Type: application/json

{
  "name": "Hlomozdat Dmytro",
  "email": "hlomosoma@gmail.com",
  "password": "dKf42ijsdf",
  "role": "HOTEL_OWNER"
}

### LOGIN

POST http://localhost/login
Content-Type: application/json

{
  "email": "dumaopus@gmail.com",
  "password": "leb1Gayyy"
}

### LOGIN
POST http://localhost/login
Content-Type: application/json

{
  "email": "hlomosoma@gmail.com",
  "password": "dKf42ijsdf"
}

### GET ME
GET http://localhost/me
Authorization: Bearer {{ownerToken}}

### GET RESERVATIONS (GRPC)
GET http://localhost/user/me/reservations
Authorization: Bearer {{userToken}}

### STREAM
http://localhost/user/rooms/{{hotelId}}
Authorization: Bearer {{ownerToken}}
## grpcurl -import-path ./proto -proto rooms_svc.proto -d '{"hotelId":"8799d1b4-a921-4d1d-bb6b-f44d0621e4d8"}' localhost:9090 RoomService/GetRoomsByHotel


### LOGIN (USER NOT FOUND)
POST http://localhost/login
Content-Type: application/json

{
  "email": "hlom23s3ma@gmail.com",
  "password": "dKf42ijsdf"
}

### LOGIN (WRONG PASSWORD)
POST http://localhost/login
Content-Type: application/json

{
  "email": "hlomosoma@gmail.com",
  "password": "dKf234"
}

### READ BY ID
GET http://localhost/user/{{userId}}
Accept: application/json

###
GET http://localhost/user/{{userId}}/html
Accept: text/html

###
GET http://localhost/user/{{userId}}/csv
Accept: text/csv

### READ BY EMAIL
GET http://localhost/user/email/hlomosoma@gmail.com
Accept: application/json

### READ ALL
GET http://localhost/user
Accept: application/json

###
GET http://localhost/user/html
Accept: text/html

###
GET http://localhost/user/csv
Accept: text/csv
