<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.ukma.spring.crooodle</groupId>
		<artifactId>crooodle</artifactId>
		<version>${revision}</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>services</artifactId>
	<packaging>pom</packaging>
	<name>Crooodle Business Services</name>
	<description>Aggregator for all business microservices (auth, user, ...)</description>

	<modules>
		<module>user-svc/client</module>
		<module>user-svc/dto</module>
		<module>user-svc/svc</module>

		<module>hotel-svc/client</module>
		<module>hotel-svc/dto</module>
		<module>hotel-svc/svc</module>

<!--		<module>reservation-svc/client</module>-->
		<module>reservation-svc/dto</module>
		<module>reservation-svc/svc</module>
	</modules>
</project>
