server:
  port: 8888

spring:
  application:
    name: config-svc

  profiles:
    active: native

  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: "file:/configs"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://discovery-svc:8761/eureka/
