apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
  labels:
    app.kubernetes.io/name: user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-svc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-svc
    spec:
      serviceAccountName: caller-sa
      containers:
        - name: user-svc
          image: user-svc:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://user-svc-db:5432/user_svc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-svc-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-svc-db-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
