server.port=8080
spring.datasource.url=jdbc:postgresql://user-svc-db:5432/user_svc
spring.datasource.username=${DB_USER:user_svc_user}
spring.datasource.password=${DB_PASS:password123}
spring.jpa.hibernate.ddl-auto=update
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=*

auth.keys.private=classpath:/keys/private_key.pem
auth.keys.public=classpath:/keys/public_key.pem

auth.admin.username=${ADMIN_USERNAME:admin@admin.com}
auth.admin.password=${ADMIN_PASSWORD:springboot}

logging.level.root=INFO
logging.level.org.springframework.web=TRACE
spring.mvc.log-request-details=true

security.jwt.secret=${JWT_SECRET:some-secret}
security.jwt.issuer=crooodle
security.jwt.access-token-minutes=60
security.internal.api-key=${API_KEY}
