spring:
  application:
    name: user-svc
  config:
    import: "optional:configserver:http://config-svc:8888"
  datasource:
    url: jdbc:postgresql://user-svc-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
