@startuml
set separator none
title Reservationsvc

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("CrooodleApplication.CrooodleApplication_boundary", "CrooodleApplication", $tags="") {
  Component(CrooodleApplication.CrooodleApplication.Utils, "Utils", $techn="Module", $descr="", $tags="", $link="")
  Component(CrooodleApplication.CrooodleApplication.Usersvc, "Usersvc", $techn="Module", $descr="", $tags="", $link="")
  Component(CrooodleApplication.CrooodleApplication.Hotelsvc, "Hotelsvc", $techn="Module", $descr="", $tags="", $link="")
  Component(CrooodleApplication.CrooodleApplication.Reservationsvc, "Reservationsvc", $techn="Module", $descr="", $tags="", $link="")
}

Rel(CrooodleApplication.CrooodleApplication.Reservationsvc, CrooodleApplication.CrooodleApplication.Utils, "depends on", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Reservationsvc, CrooodleApplication.CrooodleApplication.Hotelsvc, "uses", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Reservationsvc, CrooodleApplication.CrooodleApplication.Usersvc, "uses", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Hotelsvc, CrooodleApplication.CrooodleApplication.Utils, "depends on", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Hotelsvc, CrooodleApplication.CrooodleApplication.Usersvc, "uses", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Usersvc, CrooodleApplication.CrooodleApplication.Utils, "depends on", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Reservationsvc, CrooodleApplication.CrooodleApplication.Hotelsvc, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml