@startuml
set separator none
title Notificationsvc

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("CrooodleApplication.CrooodleApplication_boundary", "CrooodleApplication", $tags="") {
  Component(CrooodleApplication.CrooodleApplication.Usersvc, "Usersvc", $techn="Module", $descr="", $tags="", $link="")
  Component(CrooodleApplication.CrooodleApplication.Reservationsvc, "Reservationsvc", $techn="Module", $descr="", $tags="", $link="")
  Component(CrooodleApplication.CrooodleApplication.Notificationsvc, "Notificationsvc", $techn="Module", $descr="", $tags="", $link="")
}

Rel(CrooodleApplication.CrooodleApplication.Reservationsvc, CrooodleApplication.CrooodleApplication.Usersvc, "uses", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Notificationsvc, CrooodleApplication.CrooodleApplication.Reservationsvc, "listens to", $techn="", $tags="", $link="")
Rel(CrooodleApplication.CrooodleApplication.Notificationsvc, CrooodleApplication.CrooodleApplication.Usersvc, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml