apiVersion: v1
kind: Service
metadata:
  name: hotel-svc-db
  labels:
    app: hotel-svc-db
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: hotel-svc-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hotel-svc-db
spec:
  serviceName: hotel-svc-db
  replicas: 1
  selector:
    matchLabels:
      app: hotel-svc-db
  template:
    metadata:
      labels:
        app: hotel-svc-db
    spec:
      containers:
        - name: postgres
          image: postgres:18.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: hotel-svc-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["bash", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hotel-svc-db-pvc
