apiVersion: v1
kind: Service
metadata:
  name: hotel-svc
  labels:
    app.kubernetes.io/name: hotel-svc
spec:
  selector:
    app.kubernetes.io/name: hotel-svc
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
